# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-06 18:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookrecord',
            old_name='time',
            new_name='time_id',
        ),
        migrations.AlterUniqueTogether(
            name='bookrecord',
            unique_together=set([('room', 'book_date', 'time_id')]),
        ),
    ]
